name: TFB CI/CD

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: theflyingbirdsmc/TFB-Network/.github/workflows/tfb.yml@main
    secrets:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          DOCKER_REPO: ${{ secrets.DOCKER_REPO_TFB_NETWORK }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}